version: '3.6'
services:
  zookeeper:
    image: zookeeper:3.4.9
    ports:
    - '2181:2181'
    networks:
    - kplayground

  kafka:
    image: confluentinc/cp-kafka:5.0.0
    ports:
    - '29092:29092'
    networks:
    - kplayground
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    #volumes:
    #- /opt/dev/cp-kafka/data:/var/lib/kafka/data:rw
networks:
  ? kplayground